name: Eleventy Build
on:
  push:
    branches:
      - master
  schedule: 
    - cron: "0 11 * * *"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Persist npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      - name: Persist Eleventy .cache
        uses: actions/cache@v4
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache

      - name: Persist Eleventy Image Output
        id: cache-eleventy-image
        uses: actions/cache@v4
        with: 
          path: ./public/img/
          key: ${{ runner.os }}-eleventy-image-transforms

      - run: npm install
      - run: npx @11ty/eleventy 

      - name: Delete Eleventy Image Cache
        if: ${{ steps.cache-eleventy-image.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh cache delete ${{ runner.os }}-eleventy-image-transforms
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: public 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}